spring:
  application:
    name: wallet
  threads:
    virtual:
      enabled: true
  security:
    user:
      name: admin
      password: admin
server:
  port: 8080
management:
  endpoint:
      health:
        enabled: true
  endpoints:
    web:
      base-path: /api
rapidapi:
  uri: "https://realtime-crypto-prices.p.rapidapi.com/get_rates?symbol="
  host: "realtime-crypto-prices.p.rapidapi.com"
  key: "92014cca60msh7a2a98ab47c7233p127fecjsna5315968c38a"
jwt:
  expiration: 28800 # token expiration in seconds