INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Nicole', 'Martinelli', 'nicole.martinelli', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'nicole.martinelli@gmail.com',1);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Giada', 'Rinaldi','giada.rinaldi', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'giada.rinaldi@gmail.com',2);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Mia', 'Cavani', 'mia.cavani', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'mia.cavani@gmail.com',3);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Gaia', 'Garuti', 'gaia.garuti', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'gaia.garuti@gmail.com',4);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Anita', 'Lodi', 'anita.odi', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'anita.odi@gmail.com',5);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Eleonora', 'Ferrari', 'e.ferrari', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'e.ferrari@gmail.com',6);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Arianna', 'Luppi', 'a.luppi', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'a.luppi@gmail.com',7);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Vittoria', 'Piccinini', 'v.piccinini', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'v.piccinini@gmail.com',8);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Emma', 'Cisse', 'e.cisse', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'e.cisse@gmail.com',9);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Sofia', 'Rinaldi', 's.rinaldi', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 's.rinaldi@gmail.com',10);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Amelia', 'Russo', 'a.russo', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'a.russo@gmail.com',11);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Emma', 'Venturelli', 'e.venturelli', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'e.venturelli@gmail.com',12);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Asia', 'Cuoghi', 'a.cuoghi', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'a.cuoghi@gmail.com',13);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Sara', 'Morandi', 's.morandi', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 's.morandi@gmail.com',14);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Emily', 'Gozzi', 'e.mozzi', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'e.mozzi@gmail.com',15);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Amelia', 'Morandi', 'a.morandi', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'a.morandi@gmail.com',16);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Maria', 'Reggiani', 'm.reggiani', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'm.reggiani@gmail.com',17);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Diana', 'Cisse', 'd.cisse', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'd.cisse@gmail.com',18);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Nina', 'Piccinini', 'n.piccinini', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'n.piccinini@gmail.com',19);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Diletta', 'Ferrari', 'd.errari', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'd.errari@gmail.com',20);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Sara', 'Mantovani', 'smantovani', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'smantovani@gmail.com',21);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Ludovica', 'Roncaglia', 'lroncaglia', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'lroncaglia@gmail.com',22);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Margherita', 'Ansaloni', 'mansaloni', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'mansaloni@gmail.com',23);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Giulia', 'Baraldi', 'gbaraldi', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'gbaraldi@gmail.com',24);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Margherita', 'Vandelli', 'mvandelli', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'mvandelli@gmail.com',25);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Mia', 'Panini', 'mpanini', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'mpanini@gmail.com',26);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Francesca', 'Barbieri', 'fbarbieri', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'fbarbieri@gmail.com',27);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Francesca', 'Silvestri', 'f.silvestri', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'f.silvestri@gmail.com',28);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Emily', 'Bellei', 'e.bellei', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'e.bellei@gmail.com',29);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Diana', 'Morselli', 'd.morselli', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'd.morselli@gmail.com',30);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Arianna', 'Borsari', 'a.borsari', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'a.borsari@gmail.com',31);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Arianna', 'Righi', 'a.bighi', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'a.bighi@gmail.com',32);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Margherita', 'Borsari', 'm.borsari', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'm.borsari@gmail.com',33);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Anna', 'Messori', 'amessori', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'amessori@gmail.com',34);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Bianca', 'Vaccari', 'bvaccari', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'bvaccari@gmail.com',35);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Camilla', 'Garuti', 'cgaruti', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'cgaruti@gmail.com',36);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Ginevra', 'Vaccari', 'g.vaccari', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'g.vaccari@gmail.com',37);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Aurora', 'Lodi', 'a.lodi', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'a.lodi@gmail.com',38);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Giulia', 'Bergamini', 'g.bergamini', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'g.bergamini@gmail.com',39);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Marta', 'Rinaldi', 'm.rinaldi', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'm.rinaldi@gmail.com', 40);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Arianna', 'Cavani', 'a.cavani', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'a.cavani@gmail.com', 41);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Carlotta', 'Messori', 'c.messori', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'c.messori@gmail.com', 42);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Bianca', 'Neri', 'b.neri', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'b.neri@gmail.com', 43);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Mia', 'Ferrari', 'm.ferrari', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'm.ferrari@gmail.com', 44);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Carlotta', 'Cavani', 'c.cavani', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'c.cavani@gmail.com', 45);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Greta', 'Leonardi', 'g.leonardi', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'g.leonardi@gmail.com', 46);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Rebecca', 'Cisse', 'r.cisse', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'r.cisse@gmail.com', 47);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Giulia', 'Messori', 'gmessori', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'gmessori@gmail.com', 48);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Alice', 'Rinaldi', 'arinaldi', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'arinaldi@gmail.com', 49);
INSERT INTO tenants (firstname, lastname, nickname, pwd, email, version) VALUES ('Ludovica', 'Rinaldi', 'l.rinaldi', '$2a$10$v4elNdxU9rPCtGYVNKpeYOn6ob.YJRZIZw2MwlSQAdsRqCb8geXq6', 'l.rinaldi@gmail.com', 50);


INSERT INTO wallets (address, crypto, name, description, currency, quantity, tenantId, version) VALUES ('1MbeQFmHo9b69kCfFa6yBr7BQX4NzJFQq1', 'BTC', 'Sample Wallet-1', 'Sample wallet for demo', 'USD', 0.00166228046262, 1, 1);
INSERT INTO wallets (address, crypto, name, description, currency, quantity, tenantId, version) VALUES ('bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq', 'BTC', 'Sample Wallet-b', 'Sample wallet for demo', 'USD', 0.00166228046262, 1, 2);
INSERT INTO wallets (address, crypto, name, description, currency, quantity, tenantId, version) VALUES ('1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2', 'BTC', 'Sample Wallet-1', 'Sample wallet for demo', 'USD', 0.00166228046262, 1, 3);
INSERT INTO wallets (address, crypto, name, description, currency, quantity, tenantId, version) VALUES ('3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy', 'BTC', 'Sample Wallet-3', 'Sample wallet for demo', 'USD', 0.00166228046262, 1, 4);

